[build]
  base    = ""
  publish = "public"
  command = "npm run build"
  environment = { GATSBY_CPU_COUNT = "1" }

[context.production]
  environment = { GA_TRACKING_ID = "G-Q6XBC0V997" }

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
