name: Bundlewatch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Read node version from `.nvmrc` file
    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvmrc.outputs.node_version }}'

    - run: yarn
    - run: yarn bundlewatch
      env:
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
