name: Lighthouse

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - run: sleep 360  # 6 mins in seconds
      if: ${{ github.event_name == 'push' }}
    - name: Wait for deploy
      if: ${{ github.event_name == 'pull_request' }}
      uses: maddox/actions/wait-for-200@master
      env:
        URL: 'https://deploy-preview-${{ github.event.pull_request.number }}--lescapsules.netlify.app'
        SECONDS_BETWEEN_CHECKS: 60
        MAX_TRIES: 20
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.lescapsules.com/'
        netlify_site: 'lescapsules.netlify.app'
    - name: Upload report to Zeit
      run: |
        now -t ${{ secrets.ZEIT_TOKEN }} deploy ./report/https*.html | tee zeit-now.log
        TARGET_URL=`tail -n1 zeit-now.log`
        curl -X POST https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "{
            \"state\": \"success\",
            \"target_url\": \"${TARGET_URL}\",
            \"description\": \"Lighthouse report\",
            \"context\": \"lighthouse-report\"
          }"

