name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
        - eslint
        - prettier

    steps:
    - uses: actions/checkout@v2

    # Read node version from `.nvmrc` file
    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvmrc.outputs.node_version }}'

    - run: yarn
    - run: |
        yarn lint:${{ matrix.linter }}
